<?php

$lang = array(
	
	// part-header.php - part-footer.php
	'MENU_INICIO' => 'Home',
	'MENU_GALLERY' => 'Marketplace',
	'MENU_ENTRADAS' => 'Entries',
	'MENU_CONTACT' => 'Contact',

	//buttons
	
	'EXPLORE_BTN' => 'Explore',
	'VIEW_MORE_BTN' => 'see more',
	'VIEW_GALLERY_BTN' => 'see all',
	'SEND_BTN' => 'Send',
	'BUY_BTN' => 'TO BUY',
	'PREVIOUS_BTN' => 'Previous',
	'NEXT_BTN' => 'Next',
	'WANT_BUY_BTN' => 'I want to buy it',

	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',


	// index.php

	'INDEX_SECTION_ONE_TITLE' => 'Eternal captain',
	'INDEX_SECTION_ONE_PARAGRAPH_ONE' => 'The lion of a thousand battles says goodbye, the one who gave River the most amount of achievements… and his last roar will be heard in all the corners of the country.',
	'INDEX_SECTION_ONE_PARAGRAPH_TWO' => 'Leo Ponzio launches his collection of unique 3000 NFTs, generated with a great variety of properties representative of him and stored in the net of Ethereum.',
	
	'INDEX_SECTION_2_TITLE_1' => 'matches',
	'INDEX_SECTION_2_TITLE_2' => 'local titles',
	'INDEX_SECTION_2_TITLE_3' => 'international titles',
	'INDEX_SECTION_2_TITLE_4' => 'liberators',

	'INDEX_SECTION_3_TITLE' => 'Box collection',
	'INDEX_SECTION_3_PARAGRAPH' => 'In the box is Leo’s NFT collection! The purchase is 100% random based on the blockchain in the Ethereum network. They will be 3000 NFT in cartoon style with some that will be Leo’s  historical moments in 3D with sound and movement.',

	'INDEX_SECTION_4_TITLE' => 'Exclusive <br class="d-block d-xs-none">benefits for you',
	'INDEX_SECTION_4_PARAGRAPH_1' => 'By being part of the Leo and WFG community, you will be able to enjoy multiple benefits and experiences, such as private events, Discord, Airdrops, something unique and unforgettable like eating a barbecue with Leo and other colleagues of his, or even playing a few minutes in the farewell party!',
	'INDEX_SECTION_4_PARAGRAPH_2' => '* The winners will be announced after the official sale of the collection.',
	'INDEX_SECTION_4_LIST_1_CARD_1' => 'Play a few minutes in the farewell game!',
	'INDEX_SECTION_4_LIST_1_CARD_2' => 'Roast with Leo and colleagues from River!',
	'INDEX_SECTION_4_LIST_1_CARD_3' => 'Access to private group.',
	'INDEX_SECTION_4_LIST_1_CARD_4' => 'Extensive utilities for the future.',
	'INDEX_SECTION_4_LIST_1_CARD_5' => 'Photo with the Copa Libertadores.',

	'INDEX_SECTION_5_TITLE' => 'Resale market',

	'INDEX_SECTION_6_ROTATE_TITLE' => 'Roadmap',
	'INDEX_SECTION_6_TITLE' => 'Step by step to glory',
	'INDEX_SECTION_6_TIMELINE_TITLE_1' => 'September 21st',
	'INDEX_SECTION_6_TIMELINE_PARAGRAPH_1' => 'Farewell party at the Monumental!',
	'INDEX_SECTION_6_TIMELINE_TITLE_2' => 'September 23 to November 6',
	'INDEX_SECTION_6_TIMELINE_PARAGRAPH_2' => 'Official sale of the collection',
	'INDEX_SECTION_6_TIMELINE_TITLE_3' => 'September/October 2022',
	'INDEX_SECTION_6_TIMELINE_PARAGRAPH_3' => 'Draw of benefits',
	'INDEX_SECTION_6_TIMELINE_TITLE_4' => 'December 2022',
	'INDEX_SECTION_6_TIMELINE_PARAGRAPH_4' => 'First private event!',
	'INDEX_SECTION_6_TIMELINE_TITLE_5' => '2023 - ∞',
	'INDEX_SECTION_6_TIMELINE_PARAGRAPH_5' => 'Upcoming Utilities, Airdrops, Benefits and Events at WFG!',

	//contact.php

	'CONTACT_SECTION_1_ROTATE_TITLE' => 'Contact',
	'CONTACT_SECTION_1_TITLE_1' => 'LEAVE US<br>YOUR MESSAGE',
	'CONTACT_SECTION_1_TITLE_2' => 'Write your<br>concerns',
	'CONTACT_SECTION_1_LABEL_1' => 'Name',
	'CONTACT_SECTION_1_LABEL_2' => 'E-mail',
	'CONTACT_SECTION_1_LABEL_3' => 'Menssage',
	'FORM_INVALID_FEEDBACK' => 'Obligatory field',
	'FORM_REQUIRED_DATA' => 'Required data',

	//faqs.php

	'FAQS_SECTION_1_ROTATE_TITLE' => 'Frequent questions',
	'FAQS_SECTION_1_ASK_1_TITLE' => 'What is an NFT?',
	'FAQS_SECTION_1_ASK_1_REPLY' => 'Its acronym in English describes Non-Fungible Tokens. A digital asset that cannot be modified, that is unique.',
	'FAQS_SECTION_1_ASK_2_TITLE' => 'What types of NFTs are there?',
	'FAQS_SECTION_1_ASK_2_REPLY' => 'Non-fungible tokens are especially widespread in the art world, whether it is to protect simple videos and images or elaborate digital works of art. However, in principle, any virtual good can be linked or protected with a token. For example, valuables from computer games are provided with an NFT that can only be used by their owner. Virtual properties and events can also be traded with tokens. 
		<br><br>
		Specifically, there are the following uses:
		<br><br>
		NFTs for art, called NFTARTs: for works of art, collectibles, GIFs, music, etc.
		<br>
		NFT for games: for unique items in games.
		<br>
		NFT certificate: for titles, certificates, identities, patents, property rights, identifications, etc.
		<br>
		Reward-NFT: for promotions and events.
	',
	'FAQS_SECTION_1_ASK_3_TITLE' => 'What kind of collection is this?',
	'FAQS_SECTION_1_ASK_3_REPLY' => 'It is a collection of digital art to commemorate Leo Ponzio and his entire career, leaving them with a memory for life based on blockchain. In which they can form a community that is associated both from their passion for the colors of their club and with technology.',
	'FAQS_SECTION_1_ASK_4_TITLE' => 'Leo Ponzio is involved in the project?',
	'FAQS_SECTION_1_ASK_4_REPLY' => 'Yes, Leo is involved and you will be able to see all the news from his social media profiles and those of WFG.',
	'FAQS_SECTION_1_ASK_5_TITLE' => 'How many NFTs are there and at what cost are they?',
	'FAQS_SECTION_1_ASK_5_REPLY' => 'The collection will be 3,000 NFT at a cost of 100 USDT each. They should consider the FEE gas that is charged for using the Ethereum network. <br><br> <em>The price is the equivalent to Ethereum and according to its price it can be modified.</em>',
	'FAQS_SECTION_1_ASK_6_TITLE' => 'How can I buy a Ponzio NFT?',
	'FAQS_SECTION_1_ASK_6_REPLY' => 'The launch is on September 23, the official sale is on our website and you must link your Metamask wallet (download here, insert metamask download link) in the Ethereum network to be able to buy an NFT. Having said that, they only have to select the amount of NFT they want to buy and click on MINT.
		<br><br>
		The NFTs will be revealed one week after the launch date.
	',
	'FAQS_SECTION_1_ASK_7_TITLE' => 'How to credit money to a Metamask wallet?',
	'FAQS_SECTION_1_ASK_7_REPLY_ROW_1' => 'There are different ways to do it, the simplest is from Metamask select the Ethereum asset; Click on "Buy", select the intermediary company to charge the balance, select payment by credit or debit card. Then they complete a short form and they will already have the assets in their wallet!',
	'FAQS_SECTION_1_ASK_7_REPLY_ROW_2' => 'Remember that you must calculate both the cost of the MINT and the FEE for transfers.',
	'FAQS_SECTION_1_ASK_8_TITLE' => "What happens if I don't get to buy a BOX?",
	'FAQS_SECTION_1_ASK_8_REPLY' => 'If you cannot make the purchase on our website, you can buy from secondary sellers from our Opensea profile. Link:',
	'FAQS_SECTION_1_ASK_9_TITLE' => 'What happens if all the NFTs are not sold?',
	'FAQS_SECTION_1_ASK_9_REPLY' => 'In the event that more than 7 days pass and not all the NFTs have been sold, the remaining NFTs cannot be generated and those that have already been purchased will remain active.',
	'FAQS_SECTION_1_ASK_10_TITLE' => 'Is there a purchase limit per wallet?',
	'FAQS_SECTION_1_ASK_10_REPLY' => 'No, everyone will be able to buy as many NFTs as they want.',
	'FAQS_SECTION_1_ASK_11_TITLE' => 'How do I claim if I was the winner of any benefit?',
	'FAQS_SECTION_1_ASK_11_REPLY' => The draws will be communicated through our communication channels and will be announced in them.',
	'FAQS_SECTION_CONTACT_PARAGRAPH' => '
		Support contact:
		<br>
		<a href="mailto:soporte@leoponzio.com" class="link-externo">soporte@leoponzio.com</a>',
	
	// gallery.php

	'GALLERY_SECTION_1_TITLE' => 'Resale market',

	// open-nft.php

	'OPEN_NFT_TABLE_CATEGORY_TITLE_1' => 'Attributes',
	'OPEN_NFT_TABLE_ITEM_1_TITLE' => 'Background',
	'OPEN_NFT_TABLE_ITEM_2_TITLE' => 'Face',
	'OPEN_NFT_TABLE_ITEM_3_TITLE' => 'Eyes',
	'OPEN_NFT_TABLE_ITEM_4_TITLE' => 'Clothes',
	'OPEN_NFT_TABLE_ITEM_5_TITLE' => 'Tattoos',
	'OPEN_NFT_TABLE_ITEM_6_TITLE' => 'Mouth/beard',
	'OPEN_NFT_TABLE_ITEM_7_TITLE' => 'Hair',
	'OPEN_NFT_TABLE_ITEM_8_TITLE' => 'Hat',
	'OPEN_NFT_TABLE_ITEM_9_TITLE' => 'Glasses',
	'' => '',
	'' => '',
    
);

?>