<?php

$lang = array(
	
	// part-header.php - part-footer.php
	'MENU_INICIO' => 'Inicio',
	'MENU_GALLERY' => 'Marketplace',
	'MENU_ENTRADAS' => 'Entradas',
	'MENU_CONTACT' => 'Contacto',

	//buttons
	
	'EXPLORE_BTN' => 'Explorar',
	'VIEW_MORE_BTN' => 'ver más',
	'VIEW_GALLERY_BTN' => 'ver todos',
	'SEND_BTN' => 'Enviar',
	'BUY_BTN' => 'COMPRAR',
	'PREVIOUS_BTN' => 'Anterior',
	'NEXT_BTN' => 'Siguiente',
	'WANT_BUY_BTN' => 'Quiero comprarlo',

	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',


	// index.php

	'INDEX_SECTION_ONE_TITLE' => 'Capitán eterno',
	'INDEX_SECTION_ONE_PARAGRAPH_ONE' => 'Se despide el León de las mil batallas, el que le dio a River la mayor cantidad de logros… y su último rugido será escuchado en todos los rincones del país.',
	'INDEX_SECTION_ONE_PARAGRAPH_TWO' => 'Leo Ponzio lanza su colección de 3000 NFT únicos, generados con una gran variedad de propiedades representativas de él y almacenados en la red de Ethereum.',
	
	'INDEX_SECTION_2_TITLE_1' => 'partidos',
	'INDEX_SECTION_2_TITLE_2' => 'títulos locales',
	'INDEX_SECTION_2_TITLE_3' => 'títulos internacionales',
	'INDEX_SECTION_2_TITLE_4' => 'libertadores',

	'INDEX_SECTION_3_TITLE' => 'Box collection',
	'INDEX_SECTION_3_PARAGRAPH' => 'En la BOX está la colección de NFT de Leo! La compra es 100% aleatoria basada en blockchain en la red de Ethereum, serán de 3000 NFT con estilo cartoon con algunos que serán de momentos históricos de Leo en 3D con sonido y movimiento!',

	'INDEX_SECTION_4_TITLE' => 'Beneficios <br class="d-block d-xs-none">exclusivos para vos',
	'INDEX_SECTION_4_PARAGRAPH_1' => 'Por ser parte de la comunidad de Leo y WFG podrán disfrutar de múltiples beneficios y experiencias, como eventos privados, Discord, Airdrops, algo único e inolvidable como comer un asado con Leo y otros compañeros de él, o incluso ¡jugar unos minutos en el partido de despedida!',
	'INDEX_SECTION_4_PARAGRAPH_2' => '* Los ganadores se darán a conocer posterior a la venta oficial de la colección.',
	'INDEX_SECTION_4_LIST_1_CARD_1' => '¡Jugar unos minutos en el partido de despedida!',
	'INDEX_SECTION_4_LIST_1_CARD_2' => '¡Asado con Leo y compañeros de River!',
	'INDEX_SECTION_4_LIST_1_CARD_3' => 'Acceso a grupo privado.',
	'INDEX_SECTION_4_LIST_1_CARD_4' => 'Amplias utilidades para el futuro.',
	'INDEX_SECTION_4_LIST_1_CARD_5' => 'Foto con la Copa Libertadores.',

	'INDEX_SECTION_5_TITLE' => 'Marketplace',

	'INDEX_SECTION_6_ROTATE_TITLE' => 'Roadmap',
	'INDEX_SECTION_6_TITLE' => 'Paso a paso hasta la gloria',
	'INDEX_SECTION_6_TIMELINE_TITLE_1' => '21 de Septiembre',
	'INDEX_SECTION_6_TIMELINE_PARAGRAPH_1' => '¡Partido de despedida en el Monumental!',
	'INDEX_SECTION_6_TIMELINE_TITLE_2' => '23 de Septiembre a 6 de Noviembre',
	'INDEX_SECTION_6_TIMELINE_PARAGRAPH_2' => 'Venta Oficial de la colección',
	'INDEX_SECTION_6_TIMELINE_TITLE_3' => 'Septiembre/Octubre 2022',
	'INDEX_SECTION_6_TIMELINE_PARAGRAPH_3' => 'Sorteo de beneficios',
	'INDEX_SECTION_6_TIMELINE_TITLE_4' => 'Diciembre 2022',
	'INDEX_SECTION_6_TIMELINE_PARAGRAPH_4' => '¡Primer evento privado!',
	'INDEX_SECTION_6_TIMELINE_TITLE_5' => '2023 - ∞',
	'INDEX_SECTION_6_TIMELINE_PARAGRAPH_5' => '¡Próximas Utilidades, Airdrops, Beneficios y Eventos en WFG!',
	

	//contact.php

	'CONTACT_SECTION_1_ROTATE_TITLE' => 'Contacto',
	'CONTACT_SECTION_1_TITLE_1' => 'DEJANOS<br>TU MENSAJE',
	'CONTACT_SECTION_1_TITLE_2' => 'Escribí tus<br>inquietudes',
	'CONTACT_SECTION_1_LABEL_1' => 'Nombre',
	'CONTACT_SECTION_1_LABEL_2' => 'E-mail',
	'CONTACT_SECTION_1_LABEL_3' => 'Mensaje',
	'FORM_INVALID_FEEDBACK' => 'Campo Obligatorio',
	'FORM_REQUIRED_DATA' => 'Datos obligatorios',

	//faqs.php

	'FAQS_SECTION_1_ROTATE_TITLE' => 'Preguntas frecuentes',
	'FAQS_SECTION_1_ASK_1_TITLE' => '¿Qué es un NFT?',
	'FAQS_SECTION_1_ASK_1_REPLY' => 'Sus siglas en inglés describen Non-Fungible Tokens. Un activo digital que no puede ser modificado, que es único.',
	'FAQS_SECTION_1_ASK_2_TITLE' => '¿Qué tipos de NFT existen?',
	'FAQS_SECTION_1_ASK_2_REPLY' => 'Los tokens no fungibles están especialmente extendidos en el mundo del arte, ya sea para proteger simples vídeos e imágenes o elaboradas obras de arte digitales. Sin embargo, en principio, cualquier bien virtual puede vincularse o protegerse con un token. Por ejemplo, los objetos de valor de los juegos de computadora están provistos de un NFT que solo puede ser utilizado por su propietario. Las propiedades y eventos virtuales también pueden negociarse con tokens. 
		<br><br>
		En concreto, existen los siguientes usos:
		<br><br>
		NFT para arte, llamados NFTART : para obras de arte, piezas de colección, GIFs, música, etc.
		<br>
		NFT para juegos: para objetos únicos en los juegos.
		<br>
		Certificado NFT: para títulos, certificados, identidades, patentes, derechos de propiedad, identificaciones, etc.
		<br>
		Reward-NFT: para promociones y eventos.
	',
	'FAQS_SECTION_1_ASK_3_TITLE' => '¿Qué tipo de colección es esta?',
	'FAQS_SECTION_1_ASK_3_REPLY' => 'Es una colección de arte digital para conmemorar a Leo Ponzio y toda su trayectoria, dejándoles un recuerdo de por vida basado en blockchain. En la cual puedan formar una comunidad que se asocie tanto desde su pasión por los colores de su club como con la tecnología.',
	'FAQS_SECTION_1_ASK_4_TITLE' => '¿Leo Ponzio está involucrado en el proyecto?',
	'FAQS_SECTION_1_ASK_4_REPLY' => 'Sí, Leo está involucrado y podrán ir viendo todas las novedades desde sus perfiles de redes sociales y las de WFG.',
	'FAQS_SECTION_1_ASK_5_TITLE' => '¿Cuántos NFT hay y a qué costo están?',
	'FAQS_SECTION_1_ASK_5_REPLY' => 'La colección será de 3000 NFT a un costo de 100 USDT cada uno. Deberán contemplar el gas FEE que se cobra por utilizar la red de Ethereum. <br><br> <em>El precio es el equivalente a Ethereum y según el precio del mismo puede irse modificando.</em>',
	'FAQS_SECTION_1_ASK_6_TITLE' => '¿Cómo puedo comprar un NFT de Ponzio?',
	'FAQS_SECTION_1_ASK_6_REPLY' => 'El lanzamiento es el 23 de Septiembre, la venta oficial es en nuestra web y deben vincular su wallet de Metamask (descargar aquí , insertar link de descarga de metamask) en la red de Ethereum para poder comprar un NFT. Una vez dicho esto, únicamente deben seleccionar la cantidad de NFT que quieren comprar y hacer click en MINT.
		<br><br>
		Los NFT serán revelados una semana posterior a la fecha del lanzamiento
	',
	'FAQS_SECTION_1_ASK_7_TITLE' => '¿Cómo acredito dinero en una wallet de Metamask?',
	'FAQS_SECTION_1_ASK_7_REPLY_ROW_1' => 'Hay distintas formas de hacerlo, la mas simple es desde Metamask seleccionar el activo Ethereum; Hacer click en “Comprar”, seleccionar la empresa intermediaria para cargar el saldo, seleccionar pago con tarjeta de crédito o débito. Luego completan un breve formulario y ya van a estar con los activos en su wallet!',
	'FAQS_SECTION_1_ASK_7_REPLY_ROW_2' => 'Recuerden que deben calcular tanto el costo del MINT y el FEE por transferencias.',
	'FAQS_SECTION_1_ASK_8_TITLE' => '¿Qué pasa si no llego a comprar una BOX?',
	'FAQS_SECTION_1_ASK_8_REPLY' => 'En caso de no poder realizar la compra en nuestra web podrá comprar a vendedores secundarios desde nuestro perfil de Opensea. Link:',
	'FAQS_SECTION_1_ASK_9_TITLE' => '¿Qué pasa si no se vende la totalidad de los NFT?',
	'FAQS_SECTION_1_ASK_9_REPLY' => 'En caso de que pase más de 60 días y no se hayan vendido todos los NFT, los NFT restantes no podrán ser generados y quedarán activos los que ya fueron comprados.',
	'FAQS_SECTION_1_ASK_10_TITLE' => '¿Hay algún límite de compra por wallet?',
	'FAQS_SECTION_1_ASK_10_REPLY' => 'No, cada uno podrá comprar los NFT que deseen.',
	'FAQS_SECTION_1_ASK_11_TITLE' => '¿Cómo reclamo si fui ganador de algún beneficio?',
	'FAQS_SECTION_1_ASK_11_REPLY' => 'Los sorteos se comunicarán a través de nuestros canales de comunicación y se darán a conocer en los mismos.',
	'FAQS_SECTION_CONTACT_PARAGRAPH' => '
		Contacto de soporte:
		<br>
		<a href="mailto:soporte@leoponzio.com" class="link-externo">soporte@leoponzio.com</a>',
	
	
	// gallery.php

	'GALLERY_SECTION_1_TITLE' => 'Marketplace',

	// open-nft.php

	'OPEN_NFT_TABLE_CATEGORY_TITLE_1' => 'Atributos',
	'OPEN_NFT_TABLE_ITEM_1_TITLE' => 'Fondo',
	'OPEN_NFT_TABLE_ITEM_2_TITLE' => 'Cara',
	'OPEN_NFT_TABLE_ITEM_3_TITLE' => 'Ojos',
	'OPEN_NFT_TABLE_ITEM_4_TITLE' => 'Ropa',
	'OPEN_NFT_TABLE_ITEM_5_TITLE' => 'Tatuajes',
	'OPEN_NFT_TABLE_ITEM_6_TITLE' => 'Boca/barba',
	'OPEN_NFT_TABLE_ITEM_7_TITLE' => 'Pelo',
	'OPEN_NFT_TABLE_ITEM_8_TITLE' => 'Gorro',
	'OPEN_NFT_TABLE_ITEM_9_TITLE' => 'Anteojos',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
    
);

?>